# Copies the working tree's chrome.css / preferences.json / README.md into the
# Zen profile's copy of Livery and rewrites the merged mods stylesheet, so a
# restart of Zen is enough to pick the change up - no off/on toggle in Zen Mods.
# Assumes Livery is the only enabled mod (the merged file is rebuilt from it alone).
param(
    [string]$Profile = (Get-ChildItem "$env:APPDATA\zen\Profiles" -Directory | Where-Object Name -like '*Default (release)' | Select-Object -First 1 -ExpandProperty FullName)
)
$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$theme = Get-Content "$repo\theme.json" | ConvertFrom-Json
$dir = "$Profile\chrome\zen-themes\$($theme.id)"
if (-not (Test-Path $dir)) { throw "Livery is not installed in $Profile" }

Copy-Item "$repo\chrome.css" "$dir\chrome.css"
Copy-Item "$repo\preferences.json" "$dir\preferences.json"
Copy-Item "$repo\README.md" "$dir\readme.md"

$header = @"
/* Zen Mods - Generated by ZenMods.
* FILE GENERATED AT: $(Get-Date -Format 'dddd, MMMM d, yyyy \a\t h:mm:ss tt') (dev-install.ps1)
* DO NOT EDIT THIS FILE DIRECTLY!
* Your changes will be overwritten.
* Instead, go to the preferences and edit the mods there.
*/

/* Name: $($theme.name) */
/* Description: $($theme.description) */
/* Author: @$($theme.author) */
"@
$css = $header + (Get-Content "$repo\chrome.css" -Raw)
[IO.File]::WriteAllText("$Profile\chrome\zen-themes.css", $css, [Text.UTF8Encoding]::new($false))
"Installed $($theme.name) $($theme.version) into $dir; restart Zen."
